package diglex.dsl.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.constraints.IModelConstraints;
import jetbrains.mps.smodel.constraints.INodePropertyGetter;
import jetbrains.mps.smodel.constraints.INodePropertySetter;
import jetbrains.mps.smodel.constraints.ModelConstraintsManager;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.IScope;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class LexemSymbolCode_symbol_PropertyConstraint implements IModelConstraints, INodePropertyGetter, INodePropertySetter {
  public LexemSymbolCode_symbol_PropertyConstraint() {
  }

  public void registerSelf(ModelConstraintsManager manager) {
    manager.registerNodePropertyGetter("diglex.dsl.structure.LexemSymbolCode", "symbol", this);
    manager.registerNodePropertySetter("diglex.dsl.structure.LexemSymbolCode", "symbol", this);
  }

  public void unRegisterSelf(ModelConstraintsManager manager) {
    manager.unRegisterNodePropertyGetter("diglex.dsl.structure.LexemSymbolCode", "symbol");
    manager.unRegisterNodePropertySetter("diglex.dsl.structure.LexemSymbolCode", "symbol");
  }

  public Object execPropertyGet(SNode node, String propertyName, IScope scope) {
    return String.format("%c", SPropertyOperations.getInteger(node, "code"));
  }

  public void execPropertySet(final SNode node, final String propertyName, final String propertyValue, final IScope scope) {
  }
}
