package diglex.dsl.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.constraints.IModelConstraints;
import jetbrains.mps.smodel.constraints.INodePropertyGetter;
import jetbrains.mps.smodel.constraints.INodePropertySetter;
import jetbrains.mps.smodel.constraints.ModelConstraintsManager;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.IScope;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class RepeatTimes_maximumInteger_PropertyConstraint implements IModelConstraints, INodePropertyGetter, INodePropertySetter {
  public RepeatTimes_maximumInteger_PropertyConstraint() {
  }

  public void registerSelf(ModelConstraintsManager manager) {
    manager.registerNodePropertyGetter("diglex.dsl.structure.RepeatTimes", "maximumInteger", this);
    manager.registerNodePropertySetter("diglex.dsl.structure.RepeatTimes", "maximumInteger", this);
  }

  public void unRegisterSelf(ModelConstraintsManager manager) {
    manager.unRegisterNodePropertyGetter("diglex.dsl.structure.RepeatTimes", "maximumInteger");
    manager.unRegisterNodePropertySetter("diglex.dsl.structure.RepeatTimes", "maximumInteger");
  }

  public Object execPropertyGet(SNode node, String propertyName, IScope scope) {
    if (SPropertyOperations.getString(node, "maximum").equals("INF")) {
      return 2000000000;
    }
    return Integer.valueOf(SPropertyOperations.getString(node, "maximum"));
  }

  public void execPropertySet(final SNode node, final String propertyName, final String propertyValue, final IScope scope) {
  }
}
