package diglex.dsl.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.pluginparts.actions.GeneratedActionGroup;
import jetbrains.mps.logging.Logger;
import jetbrains.mps.ide.actions.Tools_ActionGroup;

public class Diglex_DSL_ActionGroup extends GeneratedActionGroup {
  private static Logger LOG = Logger.getLogger(Diglex_DSL_ActionGroup.class);
  public static final String ID = "diglex.dsl.plugin.Diglex DSL";

  public Diglex_DSL_ActionGroup() {
    super("Diglex DSL", ID);
    this.setIsInternal(false);
    this.setPopup(false);
    try {
      Diglex_DSL_ActionGroup.this.addAction("diglex.dsl.plugin.DebugDictionary_Action", "diglex.dsl");
    } catch (Throwable t) {
      LOG.error("User group error", t);
    }
  }

  public void adjust() {
    this.insertGroupIntoAnother(Tools_ActionGroup.ID, null);
  }
}
