package diglex.xml.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.lang.core.structure.INamedConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class ElementPart extends BaseConcept implements INamedConcept {
  public static final String concept = "diglex.xml.structure.ElementPart";
  public static final String NAME = "name";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";

  public ElementPart(SNode node) {
    super(node);
  }

  public String getName() {
    return this.getProperty(ElementPart.NAME);
  }

  public void setName(String value) {
    this.setProperty(ElementPart.NAME, value);
  }

  public String getShortDescription() {
    return this.getProperty(ElementPart.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(ElementPart.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(ElementPart.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(ElementPart.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(ElementPart.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(ElementPart.VIRTUAL_PACKAGE, value);
  }

  public static ElementPart newInstance(SModel sm, boolean init) {
    return (ElementPart) SModelUtil_new.instantiateConceptDeclaration("diglex.xml.structure.ElementPart", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static ElementPart newInstance(SModel sm) {
    return ElementPart.newInstance(sm, false);
  }
}
