package diglex.xml.structure;

/*Generated by MPS */

import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.Language;
import jetbrains.mps.smodel.MPSModuleRepository;

public class Xml_Language {
  public static ModuleReference MODULE_REFERENCE = ModuleReference.fromString("772f6dcd-8c0d-48f7-869c-908e036f7c8f(diglex.xml)");

  public static Language get() {
    return (Language) MPSModuleRepository.getInstance().getModule(MODULE_REFERENCE);
  }
}
