package diglex.dsl.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.DefaultNodeEditor;
import jetbrains.mps.nodeEditor.cells.EditorCell;
import jetbrains.mps.nodeEditor.EditorContext;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.nodeEditor.style.Style;
import jetbrains.mps.nodeEditor.style.StyleAttributes;
import jetbrains.mps.nodeEditor.cells.EditorCell_Constant;
import jetbrains.mps.nodeEditor.MPSColors;
import jetbrains.mps.nodeEditor.cellProviders.CellProviderWithRole;
import jetbrains.mps.lang.editor.cellProviders.PropertyCellProvider;
import jetbrains.mps.smodel.IOperationContext;
import jetbrains.mps.nodeEditor.EditorManager;

public class AnySymbol_Editor extends DefaultNodeEditor {
  public EditorCell createEditorCell(EditorContext editorContext, SNode node) {
    return this.createCollection_qg2k0k_a(editorContext, node);
  }

  private EditorCell createCollection_qg2k0k_a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createIndent2(editorContext, node);
    editorCell.setCellId("Collection_qg2k0k_a");
    editorCell.addEditorCell(this.createConstant_qg2k0k_a0(editorContext, node));
    editorCell.addEditorCell(this.createCollection_qg2k0k_b0(editorContext, node));
    return editorCell;
  }

  private EditorCell createCollection_qg2k0k_b0(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createVertical(editorContext, node);
    editorCell.setCellId("Collection_qg2k0k_b0");
    {
      Style style = editorCell.getStyle();
      style.set(StyleAttributes.INDENT_LAYOUT_ON_NEW_LINE, true);
      style.set(StyleAttributes.INDENT_LAYOUT_INDENT, true);
    }
    editorCell.addEditorCell(this.createCollection_qg2k0k_a1a(editorContext, node));
    editorCell.addEditorCell(this.createCollection_qg2k0k_b1a(editorContext, node));
    return editorCell;
  }

  private EditorCell createCollection_qg2k0k_a1a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createHorizontal(editorContext, node);
    editorCell.setCellId("Collection_qg2k0k_a1a");
    editorCell.addEditorCell(this.createConstant_qg2k0k_a0b0(editorContext, node));
    editorCell.addEditorCell(this.createProperty_qg2k0k_b0b0(editorContext, node));
    return editorCell;
  }

  private EditorCell createCollection_qg2k0k_b1a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createHorizontal(editorContext, node);
    editorCell.setCellId("Collection_qg2k0k_b1a");
    editorCell.addEditorCell(this.createConstant_qg2k0k_a1b0(editorContext, node));
    editorCell.addEditorCell(this.createProperty_qg2k0k_b1b0(editorContext, node));
    return editorCell;
  }

  private EditorCell createConstant_qg2k0k_a0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "\u041b\u044e\u0431\u043e\u0439 \u0441\u0438\u043c\u0432\u043e\u043b");
    editorCell.setCellId("Constant_qg2k0k_a0");
    {
      Style style = editorCell.getStyle();
      style.set(StyleAttributes.TEXT_COLOR, MPSColors.orange);
    }
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createConstant_qg2k0k_a0b0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "\u041c\u0438\u043d\u0438\u043c\u0443\u043c");
    editorCell.setCellId("Constant_qg2k0k_a0b0");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createConstant_qg2k0k_a1b0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "\u041c\u0430\u043a\u0441\u0438\u043c\u0443\u043c");
    editorCell.setCellId("Constant_qg2k0k_a1b0");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createProperty_qg2k0k_b0b0(EditorContext editorContext, SNode node) {
    CellProviderWithRole provider = new PropertyCellProvider(node, editorContext);
    provider.setRole("timesMinimum");
    provider.setNoTargetText("<no timesMinimum>");
    EditorCell editorCell;
    editorCell = provider.createEditorCell(editorContext);
    editorCell.setCellId("property_timesMinimum");
    {
      Style style = editorCell.getStyle();
      style.set(StyleAttributes.INDENT_LAYOUT_NEW_LINE, true);
    }
    editorCell.setSubstituteInfo(provider.createDefaultSubstituteInfo());
    SNode attributeConcept = provider.getRoleAttribute();
    Class attributeKind = provider.getRoleAttributeClass();
    if (attributeConcept != null) {
      IOperationContext opContext = editorContext.getOperationContext();
      EditorManager manager = EditorManager.getInstanceFromContext(opContext);
      return manager.createRoleAttributeCell(editorContext, attributeConcept, attributeKind, editorCell);
    } else
    return editorCell;
  }

  private EditorCell createProperty_qg2k0k_b1b0(EditorContext editorContext, SNode node) {
    CellProviderWithRole provider = new PropertyCellProvider(node, editorContext);
    provider.setRole("timesMaximum");
    provider.setNoTargetText("<no timesMaximum>");
    EditorCell editorCell;
    editorCell = provider.createEditorCell(editorContext);
    editorCell.setCellId("property_timesMaximum");
    {
      Style style = editorCell.getStyle();
      style.set(StyleAttributes.INDENT_LAYOUT_NEW_LINE, true);
    }
    editorCell.setSubstituteInfo(provider.createDefaultSubstituteInfo());
    SNode attributeConcept = provider.getRoleAttribute();
    Class attributeKind = provider.getRoleAttributeClass();
    if (attributeConcept != null) {
      IOperationContext opContext = editorContext.getOperationContext();
      EditorManager manager = EditorManager.getInstanceFromContext(opContext);
      return manager.createRoleAttributeCell(editorContext, attributeConcept, attributeKind, editorCell);
    } else
    return editorCell;
  }
}
