package diglex.dsl.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class AnySymbol_Behavior {
  public static void init(SNode thisNode) {
    SPropertyOperations.set(thisNode, "timesMaximum", "INF");
    SPropertyOperations.set(thisNode, "timesMinimum", "" + 0);
  }

  public static String virtual_getFqName_1213877404258(SNode thisNode) {
    return "*";
  }
}
