package diglex.dsl.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;

public class AnySymbol_Behavior {
  public static void init(SNode thisNode) {
  }

  public static String virtual_getFqName_1213877404258(SNode thisNode) {
    return "*";
  }
}
