package diglex.dsl.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class BlockTail_Behavior {
  public static void init(SNode thisNode) {
    SPropertyOperations.set(thisNode, "minimumLength", "" + 0);
    SPropertyOperations.set(thisNode, "maximumLength", "INF");
  }
}
