package diglex.dsl.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class ExactString_Behavior {
  public static void init(SNode thisNode) {
  }

  public static String virtual_getFqName_1213877404258(SNode thisNode) {
    return SPropertyOperations.getString(thisNode, "Value");
  }
}
