package diglex.dsl.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.baseLanguage.closures.runtime.Wrappers;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.internal.collections.runtime.IVisitor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class StringSet_Behavior {
  public static void init(SNode thisNode) {
  }

  public static String virtual_getFqName_1213877404258(SNode thisNode) {
    final Wrappers._T<String> result = new Wrappers._T<String>("");
    ListSequence.fromList(SLinkOperations.getTargets(thisNode, "Items", true)).visitAll(new IVisitor<SNode>() {
      public void visit(SNode it) {
        result.value += SPropertyOperations.getString(it, "Value") + ", ";
      }
    });
    return result.value;
  }
}
