package diglex.dsl.utils;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.generator.smodelAdapter.SEnumOperations;

public class ClassPropertyDatatypeUtil {
  public ClassPropertyDatatypeUtil() {
  }

  public static String getXmlStringRepresentation(String enumValue) {
    if (enumValue.equals(SEnumOperations.getEnumMemberValue(SEnumOperations.getEnumMember(SEnumOperations.getEnum("r:73355133-3b63-4ae4-8b45-1fe6e5a414f0(diglex.dsl.structure)", "ClassPropertyDatatype"), "\u0426\u0435\u043b\u043e\u0435")))) {
      return "int";
    }
    if (enumValue.equals(SEnumOperations.getEnumMemberValue(SEnumOperations.getEnumMember(SEnumOperations.getEnum("r:73355133-3b63-4ae4-8b45-1fe6e5a414f0(diglex.dsl.structure)", "ClassPropertyDatatype"), "\u0412\u0435\u0449\u0435\u0441\u0442\u0432\u0435\u043d\u043d\u043e\u0435")))) {
      return "float";
    }
    if (enumValue.equals(SEnumOperations.getEnumMemberValue(SEnumOperations.getEnumMember(SEnumOperations.getEnum("r:73355133-3b63-4ae4-8b45-1fe6e5a414f0(diglex.dsl.structure)", "ClassPropertyDatatype"), "\u0411\u0443\u043b\u0435\u0432\u043e")))) {
      return "boolean";
    }
    if (enumValue.equals(SEnumOperations.getEnumMemberValue(SEnumOperations.getEnumMember(SEnumOperations.getEnum("r:73355133-3b63-4ae4-8b45-1fe6e5a414f0(diglex.dsl.structure)", "ClassPropertyDatatype"), "\u0421\u0442\u0440\u043e\u043a\u0430")))) {
      return "string";
    }

    return "unknown";
  }
}
