package diglex.dsl.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class ClassProperty extends BaseConcept {
  public static final String concept = "diglex.dsl.structure.ClassProperty";
  public static final String NAME = "name";
  public static final String VALUE = "value";
  public static final String TYPE = "type";

  public ClassProperty(SNode node) {
    super(node);
  }

  public String getName() {
    return this.getProperty(ClassProperty.NAME);
  }

  public void setName(String value) {
    this.setProperty(ClassProperty.NAME, value);
  }

  public String getValue() {
    return this.getProperty(ClassProperty.VALUE);
  }

  public void setValue(String value) {
    this.setProperty(ClassProperty.VALUE, value);
  }

  public ClassPropertyDatatype getType() {
    String value = super.getProperty(ClassProperty.TYPE);
    return ClassPropertyDatatype.parseValue(value);
  }

  public void setType(ClassPropertyDatatype value) {
    super.setProperty(ClassProperty.TYPE, value.getValueAsString());
  }

  public static ClassProperty newInstance(SModel sm, boolean init) {
    return (ClassProperty) SModelUtil_new.instantiateConceptDeclaration("diglex.dsl.structure.ClassProperty", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static ClassProperty newInstance(SModel sm) {
    return ClassProperty.newInstance(sm, false);
  }
}
