package diglex.dsl.structure;

/*Generated by MPS */

import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.Language;
import jetbrains.mps.smodel.MPSModuleRepository;

public class Dsl_Language {
  public static ModuleReference MODULE_REFERENCE = ModuleReference.fromString("bdafc912-c4d6-4e59-a78e-488eda416d0f(diglex.dsl)");

  public static Language get() {
    return (Language) MPSModuleRepository.getInstance().getModule(MODULE_REFERENCE);
  }
}
