package diglex.dsl.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class ExactString extends BaseConcept implements IBlockItem {
  public static final String concept = "diglex.dsl.structure.ExactString";
  public static final String VALUE = "Value";
  public static final String NAME = "name";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String LEXEM_TYPE = "lexemType";

  public ExactString(SNode node) {
    super(node);
  }

  public String getValue() {
    return this.getProperty(ExactString.VALUE);
  }

  public void setValue(String value) {
    this.setProperty(ExactString.VALUE, value);
  }

  public String getName() {
    return this.getProperty(ExactString.NAME);
  }

  public void setName(String value) {
    this.setProperty(ExactString.NAME, value);
  }

  public String getShortDescription() {
    return this.getProperty(ExactString.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(ExactString.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(ExactString.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(ExactString.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(ExactString.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(ExactString.VIRTUAL_PACKAGE, value);
  }

  public LexemType getLexemType() {
    return (LexemType) this.getReferent(LexemType.class, ExactString.LEXEM_TYPE);
  }

  public void setLexemType(LexemType node) {
    super.setReferent(ExactString.LEXEM_TYPE, node);
  }

  public static ExactString newInstance(SModel sm, boolean init) {
    return (ExactString) SModelUtil_new.instantiateConceptDeclaration("diglex.dsl.structure.ExactString", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static ExactString newInstance(SModel sm) {
    return ExactString.newInstance(sm, false);
  }
}
