package diglex.dsl.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.INodeAdapter;

public interface ILexemSymbol extends INodeAdapter {
  public static final String concept = "diglex.dsl.structure.ILexemSymbol";
  public static final String SYMBOL = "symbol";

  public String getSymbol();
  public void setSymbol(String value);
}
