package diglex.dsl.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.INodeAdapter;

public interface IMatchCaseItem extends INodeAdapter {
  public static final String concept = "diglex.dsl.structure.IMatchCaseItem";
  public static final String REPEAT = "Repeat";

  public RepeatTimes getRepeat();
  public void setRepeat(RepeatTimes node);
}
