package diglex.dsl.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class LexemSymbol extends BaseConcept implements ILexemSymbol {
  public static final String concept = "diglex.dsl.structure.LexemSymbol";
  public static final String SYMBOL = "symbol";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";

  public LexemSymbol(SNode node) {
    super(node);
  }

  public String getSymbol() {
    return this.getProperty(LexemSymbol.SYMBOL);
  }

  public void setSymbol(String value) {
    this.setProperty(LexemSymbol.SYMBOL, value);
  }

  public String getShortDescription() {
    return this.getProperty(LexemSymbol.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(LexemSymbol.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(LexemSymbol.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(LexemSymbol.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(LexemSymbol.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(LexemSymbol.VIRTUAL_PACKAGE, value);
  }

  public static LexemSymbol newInstance(SModel sm, boolean init) {
    return (LexemSymbol) SModelUtil_new.instantiateConceptDeclaration("diglex.dsl.structure.LexemSymbol", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static LexemSymbol newInstance(SModel sm) {
    return LexemSymbol.newInstance(sm, false);
  }
}
