package diglex.dsl.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class ShortMatchCase extends BaseConcept {
  public static final String concept = "diglex.dsl.structure.ShortMatchCase";
  public static final String MATCH_CASE = "matchCase";

  public ShortMatchCase(SNode node) {
    super(node);
  }

  public MatchCase getMatchCase() {
    return (MatchCase) this.getReferent(MatchCase.class, ShortMatchCase.MATCH_CASE);
  }

  public void setMatchCase(MatchCase node) {
    super.setReferent(ShortMatchCase.MATCH_CASE, node);
  }

  public static ShortMatchCase newInstance(SModel sm, boolean init) {
    return (ShortMatchCase) SModelUtil_new.instantiateConceptDeclaration("diglex.dsl.structure.ShortMatchCase", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static ShortMatchCase newInstance(SModel sm) {
    return ShortMatchCase.newInstance(sm, false);
  }
}
