package diglex.dsl.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class TemplateClassProperty extends BaseConcept {
  public static final String concept = "diglex.dsl.structure.TemplateClassProperty";
  public static final String NAME = "name";
  public static final String VALUE = "value";
  public static final String TYPE = "type";

  public TemplateClassProperty(SNode node) {
    super(node);
  }

  public String getName() {
    return this.getProperty(TemplateClassProperty.NAME);
  }

  public void setName(String value) {
    this.setProperty(TemplateClassProperty.NAME, value);
  }

  public String getValue() {
    return this.getProperty(TemplateClassProperty.VALUE);
  }

  public void setValue(String value) {
    this.setProperty(TemplateClassProperty.VALUE, value);
  }

  public ClassPropertyDatatype getType() {
    String value = super.getProperty(TemplateClassProperty.TYPE);
    return ClassPropertyDatatype.parseValue(value);
  }

  public void setType(ClassPropertyDatatype value) {
    super.setProperty(TemplateClassProperty.TYPE, value.getValueAsString());
  }

  public static TemplateClassProperty newInstance(SModel sm, boolean init) {
    return (TemplateClassProperty) SModelUtil_new.instantiateConceptDeclaration("diglex.dsl.structure.TemplateClassProperty", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static TemplateClassProperty newInstance(SModel sm) {
    return TemplateClassProperty.newInstance(sm, false);
  }
}
