package diglex.dsl.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.BaseIntention;
import jetbrains.mps.intentions.Intention;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.nodeEditor.EditorContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class AddDistantContext_Intention extends BaseIntention implements Intention {
  public AddDistantContext_Intention() {
  }

  public String getConcept() {
    return "diglex.dsl.structure.MatchCase";
  }

  public boolean isParameterized() {
    return false;
  }

  public boolean isErrorIntention() {
    return false;
  }

  public boolean isAvailableInChildNodes() {
    return false;
  }

  public String getDescription(final SNode node, final EditorContext editorContext) {
    return "\u0414\u043e\u0431\u0430\u0432\u0438\u0442\u044c \u0414\u0438\u0441\u0442\u0430\u043d\u0442\u043d\u044b\u0439 \u043a\u043e\u043d\u0442\u0435\u043a\u0441\u0442";
  }

  public void execute(final SNode node, final EditorContext editorContext) {
    SNode distantContext = SConceptOperations.createNewNode("diglex.dsl.structure.DistantContext", null);

    // Do like we replace this with new 
    if ((ListSequence.fromList(SLinkOperations.getTargets(node, "Items", true)).last() == null)) {
      ListSequence.fromList(SLinkOperations.getTargets(node, "Items", true)).removeLastElement();
    }

    ListSequence.fromList(SLinkOperations.getTargets(node, "Items", true)).addElement(distantContext);
  }

  public String getLocationString() {
    return "diglex.dsl.intentions";
  }
}
