package diglex.dsl.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.BaseIntention;
import jetbrains.mps.intentions.Intention;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.nodeEditor.EditorContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SModelOperations;

public class InsertTemplateReferenceAfter_Intention extends BaseIntention implements Intention {
  public InsertTemplateReferenceAfter_Intention() {
  }

  public String getConcept() {
    return "diglex.dsl.structure.IMatchCaseItem";
  }

  public boolean isParameterized() {
    return false;
  }

  public boolean isErrorIntention() {
    return false;
  }

  public boolean isAvailableInChildNodes() {
    return true;
  }

  public String getDescription(final SNode node, final EditorContext editorContext) {
    return "\u0412\u0441\u0442\u0430\u0432\u0438\u0442\u044c \u0421\u0441\u044b\u043b\u043a\u0443 \u043d\u0430 \u0448\u0430\u0431\u043b\u043e\u043d";
  }

  public boolean isApplicable(final SNode node, final EditorContext editorContext) {
    if (!(this.isApplicableToNode(node, editorContext))) {
      return false;
    }
    return true;
  }

  public boolean isApplicableToNode(final SNode node, final EditorContext editorContext) {
    return SNodeOperations.isInstanceOf(SNodeOperations.getParent(node), "diglex.dsl.structure.MatchCase");
  }

  public void execute(final SNode node, final EditorContext editorContext) {
    SNode parent = SNodeOperations.getParent(node);

    if (SNodeOperations.isInstanceOf(parent, "diglex.dsl.structure.MatchCase")) {
      SNode matchCase = SNodeOperations.as(parent, "diglex.dsl.structure.MatchCase");
      SNode templateReference = SConceptOperations.createNewNode("diglex.dsl.structure.TemplateReference", null);
      SLinkOperations.setTarget(templateReference, "TemplateReference", ListSequence.fromList(SModelOperations.getRoots(SNodeOperations.getModel(SLinkOperations.getTarget(templateReference, "TemplateReference", false)), "diglex.dsl.structure.Template")).getElement(0), false);

      ListSequence.fromList(SLinkOperations.getTargets(matchCase, "Items", true)).addElement(templateReference);

      int index = ListSequence.fromList(SLinkOperations.getTargets(matchCase, "Items", true)).indexOf(node);
      ListSequence.fromList(SLinkOperations.getTargets(matchCase, "Items", true)).insertElement(index + 1, templateReference);
    }
  }

  public String getLocationString() {
    return "diglex.dsl.intentions";
  }
}
